import { Module } from '@nestjs/common';
import { CommonModule } from '../../common/common.module';
import { AuthModule } from '../auth/auth.module';
import { CoreModule } from '../core/core.module';

// Services
import {
  AccountsService,
  JournalEntryService,
  FiscalYearService,
  BanksService,
  ReportsService,
  FinancialReportsService,
  CurrencyService,
  VatService,
  PaymentMethodsService,
  WhtService,
  OpeningBalanceService,
  ExpenseRequestService,
  ExchangeRatesService,
  ReportingPeriodsService,
  BankReconciliationService,
  ConsolidationService,
  AuditTrailService,
  CompanySettingsService,
  TransferRequestService,
  PeriodLockService,
  InternalControlsReportService,
  BatchImportService,
  MiscReceiptService,
} from './services';

// Controllers
import {
  AccountsController,
  JournalEntriesController,
  FiscalYearsController,
  BanksController,
  ReportsController,
  FinancialReportsController,
  CurrenciesController,
  VatController,
  PaymentMethodsController,
  WhtController,
  OpeningBalancesController,
  ExpenseRequestsController,
  ExchangeRatesController,
  ReportingPeriodsController,
  BankReconciliationController,
  ConsolidationController,
  AuditTrailController,
  CompanySettingsController,
  PeriodLockController,
  MiscReceiptsController,
} from './controllers';

// Guards
import { FeatureGuard } from '../../common/guards/feature.guard';

@Module({
  imports: [CommonModule, AuthModule, CoreModule],
  controllers: [
    AccountsController,
    JournalEntriesController,
    FiscalYearsController,
    BanksController,
    ReportsController,
    FinancialReportsController,
    CurrenciesController,
    VatController,
    PaymentMethodsController,
    WhtController,
    OpeningBalancesController,
    ExpenseRequestsController,
    ExchangeRatesController,
    ReportingPeriodsController,
    BankReconciliationController,
    ConsolidationController,
    AuditTrailController,
    CompanySettingsController,
    PeriodLockController,
    MiscReceiptsController,
  ],
  providers: [
    AccountsService,
    JournalEntryService,
    FiscalYearService,
    BanksService,
    ReportsService,
    FinancialReportsService,
    CurrencyService,
    VatService,
    PaymentMethodsService,
    WhtService,
    OpeningBalanceService,
    ExpenseRequestService,
    ExchangeRatesService,
    ReportingPeriodsService,
    BankReconciliationService,
    ConsolidationService,
    AuditTrailService,
    CompanySettingsService,
    TransferRequestService,
    PeriodLockService,
    InternalControlsReportService,
    BatchImportService,
    MiscReceiptService,
    FeatureGuard,
  ],
  exports: [
    AccountsService,
    JournalEntryService,
    FiscalYearService,
    BanksService,
    ReportsService,
    FinancialReportsService,
    CurrencyService,
    VatService,
    PaymentMethodsService,
    WhtService,
    OpeningBalanceService,
    ExpenseRequestService,
    ExchangeRatesService,
    ReportingPeriodsService,
    BankReconciliationService,
    ConsolidationService,
    AuditTrailService,
  ],
})
export class AccountsModule {}
